"""
Django settings for Ai_Loan_System project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-b!^_4zkh^+d#xvx5w&pdfv(&dz-%26jpa+j$t--28vp0is63gu'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


CSRF_TRUSTED_ORIGINS = [
    'https://*.ngrok-free.dev',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts.apps.AccountsConfig',
    'wallet.apps.WalletConfig',


    
    'ml_engine',
    'dashboard',
    'payments',
    'loans',
    'home',
    'helpdesk',
    'notification',
    'widget_tweaks'

    

]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.TrackSecurityMiddleware',

]
# --- SESSION FIX ---
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 86400  # 1 day
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = False   # IMPORTANT for localhost
SESSION_COOKIE_SAMESITE = 'Lax' # VERY IMPORTANT

CSRF_COOKIE_SECURE = False
CSRF_COOKIE_SAMESITE = 'Lax'

ROOT_URLCONF = 'Ai_Loan_System.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'notification.context_processors.notification_count'
            ],
        },
    },
]

WSGI_APPLICATION = 'Ai_Loan_System.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/loans/apply/'
LOGOUT_REDIRECT_URL = '/accounts/login/'


MPESA_CONSUMER_KEY    = "d11ngZkQwxWbUn15bkqQXsafk7uwzvKeaNX6REFPUtRMxTA3"
MPESA_CONSUMER_SECRET = "LKDf2MeLikGkzHuhbmX8D7KkAYc7LaGXQIZA9kHqtZr9qGHpKRVk7Z8C625eeIEC"
MPESA_SHORTCODE       = "174379"
MPESA_PASSKEY         = "bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919"
MPESA_CALLBACK_URL    = "https://YOUR-NGROK-URL.ngrok-free.app/payments/mpesa/callback/"
STK_PUSH_URL          = "https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest"
TOKEN_URL             = "https://sandbox.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials"




EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = "johngathirua@gmail.com"
EMAIL_HOST_PASSWORD = "skiovbwqjiwmwocl"

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


# DeepFace KYC settings
KYC_FACE_THRESHOLD  = 0.45    # lower = stricter matching
KYC_FACE_MODEL      = "Facenet512"
KYC_ENABLED         = True    # set False to disable face check











STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'










